project(
	'stb',
	'c',
)

stb_subprj = subproject('stb-wrap')

stb_c_lexer_dep = stb_subprj.get_variable('stb_c_lexer_dep')
meson.override_dependency('stb_c_lexer-0.12', stb_c_lexer_dep)

stb_divide_dep = stb_subprj.get_variable('stb_divide_dep')
meson.override_dependency('stb_divide-0.94', stb_divide_dep)

stb_dxt_dep = stb_subprj.get_variable('stb_dxt_dep')
meson.override_dependency('stb_dxt-1.12', stb_dxt_dep)

stb_easy_font_dep = stb_subprj.get_variable('stb_easy_font_dep')
meson.override_dependency('stb_easy_font-1.1', stb_easy_font_dep)

stb_herringbone_wang_tile_dep = stb_subprj.get_variable('stb_herringbone_wang_tile_dep')
meson.override_dependency('stb_herringbone_wang_tile-0.7', stb_herringbone_wang_tile_dep)

stb_hexwave_dep = stb_subprj.get_variable('stb_hexwave_dep')
meson.override_dependency('stb_hexwave-0.5', stb_hexwave_dep)

stb_image_resize2_dep = stb_subprj.get_variable('stb_image_resize2_dep')
meson.override_dependency('stb_image_resize-2.17', stb_image_resize2_dep)
# deprecated
stb_image_resize_dep = stb_subprj.get_variable('stb_image_resize_dep')
meson.override_dependency('stb_image_resize-0.97', stb_image_resize_dep)

stb_image_write_dep = stb_subprj.get_variable('stb_image_write_dep')
meson.override_dependency('stb_image_write-1.16', stb_image_write_dep)

stb_image_dep = stb_subprj.get_variable('stb_image_dep')
meson.override_dependency('stb_image-2.30', stb_image_dep)

stb_include_dep = stb_subprj.get_variable('stb_include_dep')
meson.override_dependency('stb_include-0.02', stb_include_dep)

stb_perlin_dep = stb_subprj.get_variable('stb_perlin_dep')
meson.override_dependency('stb_perlin-0.5', stb_perlin_dep)

stb_rect_pack_dep = stb_subprj.get_variable('stb_rect_pack_dep')
meson.override_dependency('stb_rect_pack-1.01', stb_rect_pack_dep)

stb_sprintf_dep = stb_subprj.get_variable('stb_sprintf_dep')
meson.override_dependency('stb_sprintf-1.10', stb_sprintf_dep)

stb_truetype_dep = stb_subprj.get_variable('stb_truetype_dep')
meson.override_dependency('stb_truetype-1.26', stb_truetype_dep)

stb_vorbis_dep = stb_subprj.get_variable('stb_vorbis_dep')
meson.override_dependency('stb_vorbis-1.22', stb_vorbis_dep)
